permalink:           pretty

# Setup
title:               Koalapp ğŸ¨
tagline:             How to create rails API workshop for koalas
description:         ğŸ”¥ Build based on lanyon theme for jekyll and jekyll static site generator for ruby ğŸ”¥
url:                 https://paziolka.github.io
baseurl:             /koalapp

# Uncomment for local jekyll serve
# url:                 https://paziolka.github.io/koalapp
# baseurl:             ''
paginate:            100

# About/contact
author:
  name:              Ola Pazio
  url:               https://www.facebook.com/paziolka
  email:             ola.pazio@gmail.com

# Custom vars
version:             1.0.0
